# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "sd_mod" "i915" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/4e218247-e587-4a9f-842b-f7b867c7ccc4";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/40cbd4b5-59d7-4e45-99be-d88d47fd2399";
      fsType = "ext4";
    };

  fileSystems."/mnt/keys" =
    { device = "/dev/disk/by-uuid/26AA-8939";
      fsType = "vfat";
      options = [ "defaults" "users" ];
    };  

  swapDevices =
    [ { device = "/dev/disk/by-uuid/abdcac6d-703e-4979-8691-03b4d311051f"; }
    ];

  nix.maxJobs = 2;
}
